### ISSUE TITLE
pdftoraster: New version segfaults on imagetopdf output

### ISSUE THREAD

**Issue by tillkamppeter** [OpenPrinting/cups-filters#131]
The new version of pdftoraster resulting from the fix of issue #9 causes a segfault in the test suite ("`make check`") of CUPS.
You can reproduce it by taking the test JPG file of the CUPS source code (`test/testfile.jpg`, attached) and the PPD file of the test (also attached) and running the coimmand lines
```
ulimit -c unlimited
export PPD=pdftoraster-segfault.ppd.txt
cat testfile.jpg | ./imagetopdf 1 1 1 1 "" | ./pdftoraster 1 1 1 1 "" > ../out.pdf
```
This makes pdftoraster segfault and the backtrace of `gdb` is:
```
#0  cupsImageRGBToCMYK (
    in=0x564a2f44d001 <error: Cannot access memory at address 0x564a2f44d001>, out=out@entry=0x7ffce2ecb1d0 "\377", count=<optimized out>, count@entry=1)
    at cupsfilters/image-colorspace.c:756
#1  0x0000564a2dad892e in RGB8toKCMY (src=<optimized out>, 
    pixelBuf=0x7ffce2ecb1d0 "\377", x=<optimized out>, y=<optimized out>)
    at filter/pdftoraster.cxx:877
#2  0x0000564a2dad867d in convertLinePlane (src=src@entry=0x564a2f44bf51 "", 
    dst=dst@entry=0x564a2df42570 '\377' <repeats 177 times>, "\376", 
    row=row@entry=2868, plane=plane@entry=0, pixels=2400, 
    size=<optimized out>) at filter/pdftoraster.cxx:1182
#3  0x0000564a2dad6f6d in writePageImage (pageNo=1, doc=0x564a2df742f0, 
    raster=0x564a2df74690) at filter/pdftoraster.cxx:1639
#4  outPage (raster=0x564a2df74690, pageNo=1, doc=0x564a2df742f0)
    at filter/pdftoraster.cxx:1836
#5  main (argc=<optimized out>, argv=<optimized out>)
    at filter/pdftoraster.cxx:2073
```
@tanmayanand44, could you have a look and fix this?

**Comment by tillkamppeter** [comment]
I have found this problem via the following Ubuntu bug report: [Launchpad bug #1833231](https://bugs.launchpad.net/ubuntu/+source/cups-filters/+bug/1833231)

**Comment by tillkamppeter** [comment]
Sorry, forgot the attachments. Here we go:
[pdftoraster-segfault.jpg](https://user-images.githubusercontent.com/1244825/60687440-ea112100-9eae-11e9-9d2f-f2672a1e328e.jpg)
[pdftoraster-segfault.ppd.txt](https://github.com/OpenPrinting/cups-filters/files/3360489/pdftoraster-segfault.ppd.txt)
